### ISSUE TITLE
Add method log10

### ISSUE THREAD

**Issue by vikram2000b** [BoostGSoC20/Real#30]
The library already have log function which computes <i>log<sub>e</sub>x</i>. Implement log10 function, which computes <i>log<sub>10</sub>x</i>.

**Comment by HarshAgarwal-DEV** [comment]
Would like to take this issue for working, please assign me this issue @vikram2000b

**Comment by Shyam-Sunder-saini** [comment]
i want to work on this issue please assign me for this issue

**Comment by HarshAgarwal-DEV** [comment]
> i want to work on this issue please assign me for this issue

Bro actually I am working on this issue 
Can u please ask for another one

**Comment by Shyam-Sunder-saini** [comment]
Can we work together on this?

**Comment by Pranay711** [comment]
i want to work on this issue. please assign me @vikram2000b

**Comment by BiswayanPaul** [comment]
I want to work on this issue. Please assign me @vikram2000b

**Comment by vikram2000b** [comment]
@Pranay711 @Shyam-Sunder-saini @BiswayanPaul , the issue is assigned to @HarshAgarwal-DEV but you all can work on this issue. If you want to work together, you can do that too. When you complete the implementation, just add a PR. I will review it.
Don't forget to write proper comments in code and add tests for this implementation.

**Comment by i-am-atif** [comment]
I would like to work on this issue @vikram2000b

**Comment by vikram2000b** [comment]
@i-am-atif the method is needed to be in real.hpp. I don't see any way users can use this method on real numbers. And, no tests have been added.
(Your method is built for "exact_number" which is only used for the internal working of the library, the user will never use "exact_number" directly. Our method should be for "real" numbers at the end.)

**Comment by Ezio112** [comment]
Hello @vikram2000b I assume I have a pretty fair understanding of the library and I have fixed the issue on my local machine.
Would you please allow me to work on this issue.

**Comment by vikram2000b** [comment]
@Ezio112, you can make a pull request if you have implemented log10. Don't forget to add tests and proper comments.
